// Rewrites engine/tests/fixtures/INDEX.md: one row per reading on file with its match count from the runner's rules.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { compare } from '../engine/tests/fixture_compare.js';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, '..', 'engine', 'tests', 'fixtures');
const data = { constants: JSON.parse(readFileSync(join(here, '..', 'engine', 'data', 'constants.json'), 'utf8')), effects: JSON.parse(readFileSync(join(here, '..', 'engine', 'data', 'effects.json'), 'utf8')) };
const files = readdirSync(dir).filter((f) => /^\d{3}-.*\.fixture\.json$/.test(f)).sort();
const rows = [['Fixture', 'Character', 'Bar', 'Zone', 'Captured', 'Match', 'Corrections', 'Status']];
for (const f of files) {
  const fx = JSON.parse(readFileSync(join(dir, f), 'utf8'));
  const zone = Object.keys(fx.readings || {})[0] || '';
  const bar = zone ? Object.keys(fx.readings[zone])[0] : '';
  let match = 'readings pending';
  if (zone && fx.readings[zone][bar] && ['main', 'advanced'].some((p) => fx.readings[zone][bar][p] && Object.values(fx.readings[zone][bar][p]).some((v) => v != null))) {
    const { rows } = compare(fx, data);
    match = `${rows.filter((r) => r.ok).length} of ${rows.length}`;
  }
  rows.push([f.replace('.fixture.json', ''), fx.build.name || fx.name.split(' ')[1] || '', bar === 'bar2' ? 'back' : (bar === 'bar1' ? 'front' : ''), zone === 'inPvpZone' ? 'Cyrodiil' : 'outside', fx.captured || '', match, String((fx.corrections || []).length), fx.status || '']);
}
const md = ['# Readings on file', '', 'Generated by `npm run fixtures` from the fixture files; do not edit by hand.', '', ...rows.map((r, i) => `| ${r.join(' | ')} |` + (i === 0 ? `\n| ${r.map(() => '---').join(' | ')} |` : ''))].join('\n') + '\n';
writeFileSync(join(dir, 'INDEX.md'), md);
console.log(md);
